
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-master-claim
spec:
  storageClassName: yc-network-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
