version: '3.3'

services:
  post_db:
    image: mongo:${MONGO_VER}
#    command: mongod --port 27017
#    environment:
#        MONGO_INITDB_ROOT_USERNAME: ${MG_USER}
#        MONGO_INITDB_ROOT_PASSWORD: ${MG_PASS}
#        MONGO_INITDB_DATABASE: ${MG_BASE}
#    ports:
#        - '27017:27017'
    volumes:
      - post_db:/data/db
    networks:
      backend_network:
        aliases:
          - comment_db
          - post_db


  ui:
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${UI_HOST_PORT}:${UI_CONT_PORT}
    networks:
      frontend_network:
        aliases:
          - ui

  post:
    image: ${USERNAME}/post:${POST_VER}
    networks:
      backend_network:
        aliases:
          - post
      frontend_network:
        aliases:
          - post

  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      backend_network:
        aliases:
          - comment
      frontend_network:
        aliases:
          - comment

volumes:
  post_db:
  prometheus_data:

networks:
  frontend_network:
  backend_network:
