version: '3'

services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.21.0
    ports:
      - "9411:9411"
    networks:
      backend_network:
      frontend_network:

  fluentd:
    image: ${USERNAME}/fluentd:latest
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      backend_network:


  elasticsearch:
    image: elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.4.0
    container_name: kibana
    ports:
      - "5601:5601"


networks:
  backend_network:
  frontend_network:
