version: '3.3'

services:
  mongodb:
    image: mongo:${MONGO_VER}
    container_name: mongodb
    volumes:
      - post_db:/data/db
    networks:
      backend_network:
        aliases:
         - post_db
         - comment_db
         - exporter_db

  ui:
    image: ${USERNAME}/ui:${UI_VER}
    container_name: reddit-front
    ports:
     - ${UI_HOST_PORT}:${UI_CONT_PORT}/tcp
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      frontend_network:
        aliases:
         - ui
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USERNAME}/post:${POST_VER}
    container_name: reddit-post
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      backend_network:
        aliases:
          - post
      frontend_network:
        aliases:
          - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post


  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    container_name: reddit-comment
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
#      frontend_network:
#        aliases:
#          - comment
      backend_network:
        aliases:
          - comment

volumes:
  post_db:
  prometheus_data:

networks:
  frontend_network:
  backend_network:
